core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('frontend.urls', 'frontend'), namespace='frontend')),
    path('projects/', include(('projects.urls', 'projects'), namespace='projects')),
    path('management/', include(('management.urls', 'management'), namespace='management')),
    path('clientdata/', include(('clientdata.urls', 'clientdata'), namespace='clientdata')),
    path('employees/', include(('employees.urls', 'employees'), namespace='employees')),
    path('frontend/', include(('frontend.urls', 'frontend'), namespace='frontend')),
]

employees/urls.py
from django.urls import path, include
from .views import *
from . import views


urlpatterns = [
    path('', EmployeesList.as_view(), name='employees'),
    path('add/', AddEmployee.as_view(), name='add_employee'),
    path('edit/<int:pk>/', UpdateEmployee.as_view(), name='edit_employee'),
    path('delete/<int:pk>/', DeleteEmployee.as_view(), name='delete_employee'),
    
]

employees/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission

# Create your models here.


class Employee(AbstractUser):
    position = models.CharField(max_length=100)
    

    class Meta:
        db_table = 'employees_customuser'
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['-id']

employees/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User, Group


class SignUpForm(UserCreationForm):
	email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
	first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
	last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))
	last_password_set = forms.DateTimeField(label="", required=False, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Password Set'}))
	class Meta:
		model = Employee
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'is_staff','last_password_set')

	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].widget.attrs['placeholder'] = 'User Name'
		self.fields['username'].label = ''
		self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['placeholder'] = 'Password'
		self.fields['password1'].label = ''
		self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

		self.fields['password2'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
		self.fields['password2'].label = ''
		self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'
		# self.fields['is_staff'].widget.attrs['class'] = 'form-control'
		self.fields['is_staff'].widget.attrs['placeholder'] = 'Staff'
		self.fields['is_staff'].label = ''
		self.fields['is_staff'].help_text = '<span class="form-text text-muted"><small>Is this user a member of staff.</small></span>'


class EditForm(UserChangeForm):
    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(), widget=forms.CheckboxSelectMultiple, required=False)
    remove_groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(), widget=forms.CheckboxSelectMultiple, required=False)
    last_password_set = forms.DateTimeField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Password Set'}), required=False)

    class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EditForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['groups'].widget.attrs['class'] = 'form-control'
        self.fields['remove_groups'].widget.attrs['class'] = 'form-control'

employees/views.py
import datetime
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from .models import *
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
import logging
# Create your views here.



class EmployeesList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = 'employees.view_employee'
    login_url = 'frontend:login'
    model = Employee
    template_name = 'employees.html'
    context_object_name = 'employees'
    def handle_no_permission(self):
        """Se ejecuta cuando el usuario no tiene permiso para acceder."""
        if self.request.user.is_authenticated:
            logging.error(f'Acceso denegado: El usuario {self.request.user.username} intentó acceder a la seccion de empleados sin permiso.')
        else:
            logging.error(f'Acceso denegado: Un usuario anónimo intentó acceder a la seccion de empleados sin permiso.')

        # Enviar mensaje al usuario
        messages.error(self.request, 'No tienes permisos para realizar esta acción.')

        # Si es una solicitud AJAX, responder con JSON
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": False, "error": "No tienes permisos para eliminar vehículos."}, status=403)
        
        # Para solicitudes normales, redirigir al login o a otra página
        return super().handle_no_permission()

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('search')
        if search_query:
            queryset = queryset.filter(
                Q(name__icontains=search_query) |
                Q(position__icontains=search_query)
            )
        return queryset




class AddEmployee(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'employees.add_employee'
    login_url = 'frontend:login'
    model = Employee
    template_name = 'add_employee.html'
    fields = ['name', 'position']
    success_url = '/employees/'
    login_url = 'frontend:login'

    def handle_no_permission(self):
        """Se ejecuta cuando el usuario no tiene permiso para acceder."""
        if self.request.user.is_authenticated:
            logging.error(f'Acceso denegado: El usuario {self.request.user.username} intentó agregar un empleado sin permiso.')
        else:
            logging.error(f'Acceso denegado: Un usuario anónimo intentó agregar un empleado sin permiso.')

        # Enviar mensaje al usuario
        messages.error(self.request, 'No tienes permisos para realizar esta acción.')

        # Si es una solicitud AJAX, responder con JSON
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": False, "error": "No tienes permisos para eliminar vehículos."}, status=403)
        
        # Para solicitudes normales, redirigir al login o a otra página
        return super().handle_no_permission()

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Empleado agregado correctamente')
        logging.info(self.request.user.username + ' ha agregado un nuevo empleado.')

        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": True})
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Error al agregar el empleado. Por favor intentelo de nuevo.')
        logging.error(self.request.user.username + ' ha intentado agregar un empleado pero ha fallado.')

        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": False, "error": form.errors}, status=400)
        return super().form_invalid(form)


class UpdateEmployee(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'employees.change_employee'
    model = Employee
    template_name = 'edit_employee.html'
    fields = ['name', 'position']
    success_url = '/employees/'
    login_url = 'frontend:login'

    def handle_no_permission(self):
        current_employee = Employee.objects.get(pk=self.kwargs['pk'])
        """Se ejecuta cuando el usuario no tiene permiso para acceder."""
        if self.request.user.is_authenticated:
            logging.error(f'Acceso denegado: El usuario {self.request.user.username} intentó actualizar el empleado {current_employee.username} sin permiso.')
        else:
            logging.error(f'Acceso denegado: Un usuario anónimo intentó actualizar el empleado {current_employee.username} sin permiso.')

        # Enviar mensaje al usuario
        messages.error(self.request, 'No tienes permisos para realizar esta acción.')

        # Si es una solicitud AJAX, responder con JSON
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": False, "error": "No tienes permisos para eliminar vehículos."}, status=403)
        
        # Para solicitudes normales, redirigir al login o a otra página
        return super().handle_no_permission()
    
    def form_valid(self, form):
        current_employee = Employee.objects.get(pk=self.kwargs['pk'])
        form.save()
        messages.success(self.request, 'Empleado actualizado correctamente')
        logging.info(f'El usuario {self.request.user.username} ha actualizado el empleado {current_employee.username}.')

        # Respuesta AJAX
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": True})
        return super().form_valid(form)

    def form_invalid(self, form):
        current_employee = Employee.objects.get(pk=self.kwargs['pk'])
        messages.error(self.request, 'Error al actualizar el Empleado.')
        logging.error(f'El usuario {self.request.user.username} ha intentado actualizar el empleado {current_employee.username} pero ha fallado.')
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": False, "error": form.errors.as_json()}, status=400)
        return super().form_invalid(form)
    


class DeleteEmployee(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'employees.delete_employee'
    model = Employee
    template_name = 'delete_employee.html'
    success_url = '/employees/'
    login_url = 'frontend:login'
    def handle_no_permission(self):
        current_employee = Employee.objects.get(pk=self.kwargs['pk'])
        """Se ejecuta cuando el usuario no tiene permiso para acceder."""
        if self.request.user.is_authenticated:
            logging.error(f'Acceso denegado: El usuario {self.request.user.username} intentó eliminar el empleado {current_employee.username} sin permiso.')
        else:
            logging.error(f'Acceso denegado: Un usuario anónimo intentó eliminar el empleado {current_employee.username} sin permiso.')

        # Enviar mensaje al usuario
        messages.error(self.request, 'No tienes permisos para realizar esta acción.')

        # Si es una solicitud AJAX, responder con JSON
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": False, "error": "No tienes permisos para eliminar vehículos."}, status=403)
        
        # Para solicitudes normales, redirigir al login o a otra página
        return super().handle_no_permission()

    def delete(self, request, *args, **kwargs):
        current_employee = Employee.objects.get(pk=self.kwargs['pk'])
        employee = self.get_object()  # Obtener el cliente a eliminar
        
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':  # Si es AJAX
            try:
                employee.delete()  # Eliminar el cliente
                logging.info(f'El usuario {self.request.user.username} ha eliminado el empleado {current_employee.username}.')  # Registrar el evento en el log
                return JsonResponse({"success": True, "message": "Empleado eliminado correctamente"})
            except Exception as e:
                # Enviar el mensaje de error si ocurre una excepción
                messages.error(self.request, f'Error al eliminar el Empleado: {str(e)}')  # Mensaje de error
                logging.error(f'El usuario {self.request.user.username} ha intentado eliminar el empleado {current_employee.username} pero ha fallado.')  # Registrar el evento
                return JsonResponse({"success": False, "error": str(e)}, status=400)

        # Si no es AJAX, procesar la solicitud normalmente
        messages.success(self.request, 'Empleado eliminado correctamente')
        logging.info(f'El usuario {self.request.user.username} ha eliminado el empleado {current_employee.username}.')  # Registrar el evento en el log
        return super().delete(request, *args, **kwargs)

employees/templates/add_employee.html
<!-- Modal -->
<div class="modal fade" id="addEmployee" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Agregar Empleado</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="addEmployeeForm" method="POST" action="{% url 'employees:add_employee' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Username:</label>
                        <input type="text" class="form-control" name="username" id="id_username">
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Password:</label>
                        <input type="password" class="form-control" name="password" id="id_password">
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Confirmar Password:</label>
                        <input type="password" class="form-control" name="password-confirm" id="id_password-confirm">
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Nombre:</label>
                        <input type="text" class="form-control" name="firstname" id="id_firstname">
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Apellidos:</label>
                        <input type="text" class="form-control" name="lastname" id="id_lastname">
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Email:</label>
                        <input type="text" class="form-control" name="email" id="id_email">
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Posicion:</label>
                        <input type="text" class="form-control" name="position" id="id_position">
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Is Staff:</label>
                        <input type="checkbox" name="is-staff" id="id_is-staff">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" id="saveEmployeeBtn">Guardar</button>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap y jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<!-- Script para enviar el formulario por AJAX -->
<script>
$(document).ready(function() {
    // Cuando se haga clic en el botón "Guardar"
    $('#saveEmployeeBtn').click(function(event) {
        event.preventDefault(); // Evita la recarga de la página

        var form = $("#addEmployeeForm");
        var formData = form.serialize(); // Serializa los datos del formulario

        $.ajax({
            type: form.attr("method"),
            url: form.attr("action"),
            data: formData,
            success: function(response) {
                if (response.success) {
                    $('#addEmployee').modal('hide'); // Cierra el modal
                    location.reload(); // Recarga la página para mostrar los cambios
                } else {
                    alert("Error: " + response.error);
                }
            },
            error: function(xhr) {
                alert("Error al guardar el Empleado. Inténtalo de nuevo.");
            }
        });
    });
});
</script>

employees/templates/delete_employee.html
<!-- Modal para Eliminar Cliente -->
<div class="modal fade" id="deleteEmployeeModal" tabindex="-1" aria-labelledby="deleteEmployeeLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteEmployeeLabel">Eliminar Empleado</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>¿Estás seguro de que deseas eliminar este empleado?</p>
                <input type="hidden" name="employee_id" id="delete_employee_id">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger" id="confirmDeleteEmployeeBtn">Eliminar</button>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap y jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<!-- Script para Eliminar Cliente -->
<script>
    $(document).ready(function() {
        // Mostrar el modal de eliminación con el ID del empleado
        $('.delete-employee-btn').click(function() {
            var employeeId = $(this).data('id'); // Obtener el ID del empleado
            
            $('#delete_employee_id').val(employeeId);
            $('#deleteEmployeeModal').modal('show');
        });
        
    
        // Confirmar la eliminación del empleado
        $('#confirmDeleteEmployeeBtn').click(function() {
    var employeeId = $('#delete_employee_id').val(); // Obtener el ID del empleado
    

    if (!employeeId) {
        alert("Error: No se encontró el ID del empleado.");
        return;
    }

    $.ajax({
        type: "POST",
        url: `delete/${employeeId}/`,  // Asegúrate de que esta URL es correcta
        data: {
            "csrfmiddlewaretoken": $('[name="csrfmiddlewaretoken"]').val()
        },
        success: function(response) {
            if (response.success) {
                $('#deleteEmployeeModal').modal('hide');
                location.reload();
            } else {
                location.reload();
                response.success
            }
        },
        error: function(xhr, status, error) {
            var errorMessage = xhr.responseJSON && xhr.responseJSON.error ? xhr.responseJSON.error : "Error al eliminar el empleado.";
            alert(errorMessage);
        }
    });
});

    });
    
    </script>

employees/templates/edit_employee.html
<!-- Modal para Editar Cliente -->
<div class="modal fade" id="editEmployeeModal" tabindex="-1" aria-labelledby="editEmployeeLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editEmployeeLabel">Editar Empleado</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="editEmployeeForm" method="POST" action="">
                    {% csrf_token %}
                    <input type="hidden" name="employee_id" id="edit_employee_id"> <!-- ID del empleado -->
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Username:</label>
                        <input type="text" class="form-control" name="username" id="id_username">
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Password:</label>
                        <input type="password" class="form-control" name="password" id="id_password">
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Nombre:</label>
                        <input type="text" class="form-control" name="firstname" id="id_firstname">
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Apellidos:</label>
                        <input type="text" class="form-control" name="lastname" id="id_lastname">
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Email:</label>
                        <input type="text" class="form-control" name="email" id="id_email">
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Posicion:</label>
                        <input type="text" class="form-control" name="position" id="id_position">
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Is Staff:</label>
                        <input type="checkbox" name="is-staff" id="id_is-staff">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" id="saveEditEmployeeBtn">Guardar Cambios</button>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap y jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<!-- Script para Cargar Datos en el Modal y Guardar Cambios -->
<script>
$(document).ready(function() {
    // Obtener CSRF token
    function getCSRFToken() {
        return document.querySelector('[name=csrfmiddlewaretoken]').value;
    }

    // Mostrar modal con datos del cliente
    $('.edit-client-btn').click(function() {
        var employeeId = $(this).data('id');
        var employeeName = $(this).data('firstname');
        var employeeLastname = $(this).data('lastname');
        var employeeEmail = $(this).data('email');
        var employeeUsername = $(this).data('username');
        var employeeIsStaff = $(this).data('is-staff') === 'True'; // Convertir a booleano
        var employeePassword = $(this).data('password');
        var employeePosition = $(this).data('position');

        // Rellenar los campos del formulario con los datos del cliente
        $('#edit_employee_id').val(employeeId);
        $('#edit_firstname').val(employeeName);
        $('#edit_lastname').val(employeeLastname);
        $('#edit_email').val(employeeEmail);
        $('#edit_username').val(employeeUsername);
        $('#edit_password').val(employeePassword);
        $('#edit_is-staff').prop('checked', employeeIsStaff);

        $('#edit_position').val(employeePosition);

        // Establecer la URL de la acción del formulario dinámicamente
        $('#editEmployeeForm').attr('action', `/employees/edit/${employeeId}/`);


        // Mostrar el modal
        $('#editEmployeeModal').modal('show');
    });

    // Guardar los cambios en el cliente con AJAX
    $('#saveEditEmployeeBtn').click(function(event) {
        event.preventDefault(); // Evita recargar la página

        var form = $("#editEmployeeForm");
        var formData = form.serialize(); // Serializa los datos del formulario

        $.ajax({
            type: "POST",
            url: form.attr("action"),
            data: formData,
            headers: {
                "X-CSRFToken": getCSRFToken()
            },
            success: function(response) {
                if (response.success) {
                    $('#editEmployeeModal').modal('hide'); // Cerrar modal
                    location.reload(); // Recargar página para ver cambios
                } else {
                    alert("Error: " + JSON.stringify(response.error));
                }
            },
            error: function(xhr) {
                alert("Error al actualizar el empleado. Inténtalo de nuevo.");
            }
        });
    });
});
</script>

employees/templates/employees.html
{% extends 'base.html' %}

{%block title %} Empleados {%endblock%}

{% block content %}

<div class="row mb-3 mx-3">
    <div class="col-md-12 d-flex justify-content-between align-items-center">
        <!-- Formulario de búsqueda alineado a la izquierda -->
        <form method="GET" action="{% url 'employees:employees' %}" class="form-inline d-flex">
            <input name="search" class="form-control mr-2" type="search" placeholder="Buscar">
            <button type="submit" class="btn btn-outline-success mx-2">Buscar</button>
        </form>

        <!-- Botón "Agregar Cliente" alineado a la derecha -->
        <a href="{% url 'admin:employees_employee_add' %}" class="btn btn-primary button-41" style="min-width: 150px;" target="_blank">
            Agregar Empleado
        </a>
    </div>
</div>



<div class="container-fluid">
    <table class="table align-middle mb-0 bg-white">
        <thead class="bg-light">
            <tr>
                <th>Username</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Email</th>
                <th>Posicion</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for employee in employees %}
            {% if employee.is_superuser %}
            {% else %}
                <tr>
                    <td>{{employee.username}}</td>
                    <td>{{employee.first_name}}</td>
                    <td>{{employee.last_name}}</td>
                    <td>{{employee.email}}</td>
                    <td>{{employee.position}}</td>
                    <td>
                        <a href="{% url 'admin:employees_employee_change' employee.id %}" class="btn btn-primary btn-sm" target="_blank">
                            Editar
                        </a>
                        <a href="{% url 'admin:auth_user_password_change' employee.id %}" class="btn btn-warning btn-sm" target="_blank">
                            Cambiar Password
                        </a>
                        <a href="{% url 'admin:employees_employee_delete' employee.id %}" class="btn btn-danger btn-sm" target="_blank">
                            Eliminar
                        </a>
                    </td>
                </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>

{%endblock%}