core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('frontend.urls', 'frontend'), namespace='frontend')),
    path('projects/', include(('projects.urls', 'projects'), namespace='projects')),
    path('management/', include(('management.urls', 'management'), namespace='management')),
    path('clientdata/', include(('clientdata.urls', 'clientdata'), namespace='clientdata')),
    path('employees/', include(('employees.urls', 'employees'), namespace='employees')),
    path('frontend/', include(('frontend.urls', 'frontend'), namespace='frontend')),
]

projects/urls.py
from django.urls import path, include
from .views import *
from . import views


urlpatterns = [
    path('', ProjectsView.as_view(), name='projects'),
    path('add/', AddProject.as_view(), name='add_project'),
    path('edit/<int:pk>/', views.edit_project, name='edit_project'),
    path('delete/<int:pk>/', DeleteProject.as_view(), name='delete_project'),
    path('project_details/<int:pk>/', ProjectDetails.as_view(), name='project_details'),
    path('tasks/', Tasks.as_view(), name='tasks'),
    path('task/add_task/', Createtask.as_view(), name='add_task'),
    path('task/edit_task/<int:task_id>/', views.edit_task, name='edit_task'),
    path('task/delete/<int:pk>/', Deletetask.as_view(), name='delete_task'),
    path('task/task_details/<int:pk>/', ViewTask.as_view(), name='task_details'),
    path('task/task_details/add_comment/', CreateComment.as_view(), name='add_comment'),
    path('task/task_details/edit_comment/<int:pk>/', UpdateComment.as_view(), name='edit_comment'),
    path('task/task_details/delete_comment/<int:pk>/', DeleteComment.as_view(), name='delete_comment'),
    path('email/', email_report, name='email_report'),
]

projects/models.py
import datetime
from django.db import models
from clientdata.models import Client, Car
from employees.models import Employee

# Create your models here.



class Project(models.Model):
    all_status = {
        "Pendiente": "Pendiente",
        "En progreso": "En progreso",
        "Completado": "Completado",
    }
    title = models.CharField(max_length=200)
    description = models.TextField()
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    created_at = models.DateField(auto_now=False, null=True, blank=True)
    created_by = models.CharField(max_length=100, null=True, blank=True)
    updated_at = models.DateField(auto_now=False)
    updated_by = models.CharField(max_length=100, null=True, blank=True)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(max_length=100, choices=all_status, default='Pendiente')
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    car = models.ForeignKey(Car, on_delete=models.CASCADE, null=True, blank=True)
    car_kms = models.CharField(max_length=100,null=True, blank=True)

    def __str__(self):
        return f"{self.title} - {self.client.name}"
    
    class Meta:
        db_table = "projects"
        verbose_name = "Project"
        verbose_name_plural = "Projects"
        ordering = ["-id"]




class Task(models.Model):
    all_status = {
        "Pendiente": "Pendiente",
        "En progreso": "En progreso",
        "Completado": "Completado",
    }
    title = models.CharField(max_length=200)
    description = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    created_by = models.CharField(max_length=100, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=False, null=True, blank=True)
    updated_by = models.CharField(max_length=100, null=True, blank=True)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(max_length=100, choices=all_status, default='Pendiente')
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)


    def __str__(self):
        return f"{self.title} - {self.project.title}"
    
    class Meta:
        db_table = "tasks"
        verbose_name = "Task"
        verbose_name_plural = "Tasks"
        ordering = ["-id"]


class Comment(models.Model):

    task = models.ForeignKey(Task, on_delete=models.DO_NOTHING, blank=True, related_name='comments_intask')
    text = models.TextField(max_length=5000)
    created_by = models.CharField(max_length=100, null=False, blank=True, default="")
    created_at = models.DateTimeField(default=datetime.datetime.now())
    updated_by = models.CharField(max_length=100, null=False, blank=True, default="")
    updated_at = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f"{self.task.title + ' - ' + self.created_by}"
    
    class Meta:
        db_table = 'comments'
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
        ordering = ['-id']

projects/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView, TemplateView
from .models import *
from django.db.models import Q
from django.contrib import messages
from .forms import *
import datetime
from django.utils import timezone
from django.core.exceptions import PermissionDenied
from clientdata.models import CarHistory, Car
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
import logging
from django.template.loader import render_to_string
from django.core.mail import send_mail, EmailMessage

# Create your views here.



class ProjectsView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = 'projects.view_project'
    login_url = 'frontend:login'
    model = Project
    template_name = 'projects.html'
    context_object_name = 'projects'

    def handle_no_permission(self):
        """Se ejecuta cuando el usuario no tiene permiso para acceder."""
        if self.request.user.is_authenticated:
            logging.error(f'Acceso denegado: El usuario {self.request.user.username} intentó acceder a las seccion de proyectos sin permiso.')
        else:
            logging.error(f'Acceso denegado: Un usuario anónimo intentó acceder a las seccion de proyectos sin permiso.')

        # Enviar mensaje al usuario
        messages.error(self.request, 'No tienes permisos para realizar esta acción.')

        # Si es una solicitud AJAX, responder con JSON
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": False, "error": "No tienes permisos para eliminar vehículos."}, status=403)
        
        # Para solicitudes normales, redirigir al login o a otra página
        return super().handle_no_permission()


    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('search')
        if search_query:
            queryset = queryset.filter(
                Q(title__icontains=search_query) |
                Q(client__icontains=search_query) |
                Q(status__icontains=search_query) |
                Q(employee__icontains=search_query)
            )
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ProjectForm()  # Agrega el formulario al contexto
        return context


class AddProject(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'projects.add_project'
    login_url = 'frontend:login'
    model = Project
    template_name = 'add_project.html'
    form_class = ProjectForm
    success_url = reverse_lazy('projects:projects')

    def handle_no_permission(self):
        """Se ejecuta cuando el usuario no tiene permiso para acceder."""
        if self.request.user.is_authenticated:
            logging.error(f'Acceso denegado: El usuario {self.request.user.username} intentó agregar un proyecto sin permiso.')
        else:
            logging.error(f'Acceso denegado: Un usuario anónimo intentó agregar un proyecto sin permiso.')

        # Enviar mensaje al usuario
        messages.error(self.request, 'No tienes permisos para realizar esta acción.')

        # Si es una solicitud AJAX, responder con JSON
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": False, "error": "No tienes permisos para acceder."}, status=403)
        
        # Para solicitudes normales, redirigir al login o a otra página
        return super().handle_no_permission()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
    
        client_id = self.request.GET.get('client')
        client = Client.objects.filter(pk=client_id).first() if client_id else None
    
        context['form'] = ProjectForm(client=client)
        return context

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        client_id = self.request.GET.get('client')
    
        print(f"Client ID: {client_id}")  # Verifica el client_id
    
        if client_id:
            cars = Car.objects.filter(client_id=client_id)
            print(f"Cars for client: {cars}") #Imprime los coches filtrados
            form.fields['car'].queryset = cars
        else:
            cars = Car.objects.all()
            print(f"All cars: {cars}") #Imprime todos los coches.
            form.fields['car'].queryset = cars
    
        print(f"Car field queryset: {form.fields['car'].queryset}") #Imprime el queryset final del campo car.
    
        return form

        
    def form_valid(self, form):
        print("Formulario recibido:", form.cleaned_data)
        form.instance.created_by = self.request.user.username
        form.instance.created_at = datetime.datetime.now()
        form.instance.updated_by = self.request.user.username
        form.instance.updated_at = datetime.datetime.now()
        form.instance.status = 'Pendiente'

        client = form.cleaned_data.get('client')
        car = form.cleaned_data.get('car')

        print(f" Cliente seleccionado: {client.id if client else 'Ninguno'}")
        print(f" Auto seleccionado: {car.id if car else 'Ninguno'}")

        if client and car:
            if car.client != client:
                logging.error(" ERROR: El auto seleccionado no pertenece al cliente")
                return JsonResponse(
                    {"success": False, "error": {"car": [{"message": "El vehículo seleccionado no pertenece a este cliente.", "code": "invalid_choice"}]}},
                    status=400
                )

        form.save()
        logging.info(f"El usuario {self.request.user.username} ha agregado un nuevo proyecto.")
        messages.success(self.request, 'Proyecto agregado correctamente')

        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": True})

        return super().form_valid(form)



    def form_invalid(self, form):
        logging.error(self.request.user.username + ' ha intentado agregar un proyecto pero ha fallado.')

        # 🔹 Agrega los errores del formulario en el mensaje
        errors = form.errors.as_json()
        messages.error(self.request, 'Error al agregar el proyecto. Inténtalo de nuevo.')

        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": False, "error": errors}, status=400)

        return super().form_invalid(form)
    
    # def save_car_project(self, car, project):
    #     car_history = CarHistory.objects.create(
    #         car=car,
    #         service=project,
    #     )
    #     return car_history




@permission_required('projects.change_project', raise_exception=True)
@login_required
def edit_project(request, pk):
    project = get_object_or_404(Project, pk=pk)

    if request.method == 'POST' and request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        form = ProjectForm(request.POST, instance=project, client=project.client)

        if form.is_valid():
            form.instance.updated_by = request.user.username
            form.instance.updated_at = timezone.now()
            form.save()
            return JsonResponse({'success': True})
        else:
            # Captura los errores si el formulario no es válido
            print("Form errors:", form.errors)  # Esto imprime en el log del servidor
            return JsonResponse({'success': False, 'errors': form.errors}, status=400)

    return JsonResponse({'success': False, 'error': 'Método no permitido'}, status=405)

    
    # def get_form(self, form_class=None):
    #     form = super().get_form(form_class)

    #     if not self.request.user.is_staff and not self.request.user.is_superuser:
    #         form.fields['username'].disabled = True
    #         form.fields['description'].disabled = True
    #         form.fields['start_date'].disabled = True
    #         form.fields['end_date'].disabled = True
    #         form.fields['status'].disabled = True
    #         form.fields['employee'].disabled = True
    #     return form


class DeleteProject(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'projects.delete_project'
    login_url = 'frontend:login'
    model = Project
    success_url = reverse_lazy('projects:projects')  # Se usa solo si NO es AJAX


    def handle_no_permission(self):
        current_project = Project.objects.get(pk=self.kwargs['pk'])
        """Se ejecuta cuando el usuario no tiene permiso para acceder."""
        if self.request.user.is_authenticated:
            logging.error(f'Acceso denegado: El usuario {self.request.user.username} intentó eliminar el proyecto {current_project.title} del cliente {current_project.client.name} sin permiso.')
        else:
            logging.error(f'Acceso denegado: Un usuario anónimo intentó eliminar el proyecto {current_project.title} del cliente {current_project.client.name} sin permiso.')

        # Enviar mensaje al usuario
        messages.error(self.request, 'No tienes permisos para realizar esta acción.')

        # Si es una solicitud AJAX, responder con JSON
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({"success": False, "error": "No tienes permisos para eliminar vehículos."}, status=403)
        
        # Para solicitudes normales, redirigir al login o a otra página
        return super().handle_no_permission()

    def post(self, request, *args, **kwargs):
        current_project = Project.objects.get(pk=self.request.GET.get('pk'))

projects/templates/add_project.html
<!-- Modal -->
<div class="modal fade" id="addProject" tabindex="-1" aria-labelledby="addProjectLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addProjectLabel">Agregar Proyecto</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="addProjectForm" method="POST" action="{% url 'projects:add_project' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" id="saveProjectBtn">Guardar</button>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap y jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<!-- Script para enviar el formulario por AJAX -->
<script>
$(document).ready(function() {
    $('#saveProjectBtn').click(function(event) {
        event.preventDefault();

        var form = $('#addProjectForm');
        var formData = form.serialize();

        $.ajax({
            type: form.attr('method'),
            url: form.attr('action'),
            data: formData,
            success: function(response) {
                if (response.success) {
                    $('#addProject').modal('hide');
                    location.reload();
                } else {
                    alert("Error: " + response.error);
                }
            },
            error: function(xhr) {
                alert("Error al guardar el proyecto. Inténtalo de nuevo.");
            }
        });
    });
});
</script>

projects/templates/comment_form.html
<form hx-post="{% url 'projects:add_comment' pk=task_id %}" hx-target="#comment-form-container" hx-swap="outerHTML">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>

projects/templates/create_comment.html
<!-- Modal -->
<div class="modal fade" id="addCommentModal" tabindex="-1" aria-labelledby="addCommentModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addCommentModalLabel">Agregar Comentario</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="addCommentForm" method="POST" action="{% url 'projects:add_comment' %}">
                    {% csrf_token %}
                    <label for="id_text" class="col-form-label">Comentario:</label>
                    {{ form.text }}
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" id="saveCommentBtn">Guardar</button>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap y jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<!-- Script para enviar el formulario por AJAX -->
<script>
    $(document).ready(function() {
        $('#saveCommentBtn').click(function(event) {
            event.preventDefault();
            var form = $("#addCommentForm");
            var formData = form.serialize();
            var taskId = "{{ task.id }}"; // Obtiene task_id del contexto de Django
    
            $.ajax({
                type: form.attr("method"),
                url: form.attr("action") + "?task_id=" + taskId, // Añade task_id a la URL
                data: formData,
                success: function(response) {
                    if (response.success) {
                        $('#addCommentModal').modal('hide');
                        location.reload();
                    } else {
                        alert("Error: " + response.error);
                    }
                },
                error: function(xhr, status, error) {
                    alert("Error al guardar el comentario. Inténtalo de nuevo.");
                }
            });
        });
    });
</script>

projects/templates/create_task.html
<!-- Modal -->
<div class="modal fade" id="addTaskModal" tabindex="-1" aria-labelledby="addTaskModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addTaskModalLabel">Agregar Tarea</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="addTaskForm" method="POST" action="{% url 'projects:add_task' %}">
                    {% csrf_token %}
                    <label for="id_title" class="col-form-label">Tarea:</label>
                    {{ form.title }}
                    <label for="id_description" class="col-form-label">Descripción:</label>
                    {{ form.description }}
                    <label for="id_description" class="col-form-label">Tecnico Asignado:</label>
                    {{ form.employee }}
                    <label for="id_description" class="col-form-label">Estado:</label>
                    {{ form.status }}
                    <label for="id_description" class="col-form-label">Fecha de Inicio:</label>
                    {{ form.start_date}}
                    <label for="id_description" class="col-form-label">Fecha de Fin:</label>
                    {{ form.end_date}}
                    {{ form.project.as_hidden }}
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" id="saveTaskBtn">Guardar</button>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap y jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<!-- Script para enviar el formulario por AJAX -->
<script>
    $(document).ready(function() {
        $('#saveTaskBtn').click(function(event) {
            event.preventDefault();
            var form = $("#addTaskForm");
            var formData = form.serialize();
            $.ajax({
                type: form.attr("method"),
                url: form.attr("action"),
                data: formData,
                success: function(response) {
                    if (response.success) {
                        $('#addTaskModal').modal('hide');
                        location.reload();
                    } else {
                        alert("Error: " + response.error);
                    }
                },
                error: function(xhr, status, error) {
                    alert("Error al guardar la tarea. Inténtalo de nuevo.");
                }
            });
        });
    });
</script>

projects/templates/project_details.html
{% extends 'base.html' %}

{% block title %} Proyecto #{{ project_id }} {% endblock %}

{% block content %}
<h2 class="mb-0 text-center">Detalles del Proyecto</h2>
<div class="d-flex justify-content-center">
    <form method="post" action="{% url 'projects:project_details' project.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-sm">Enviar Reporte</button>
    </form>
</div>
<br>
<main role="main" class="main-content">
    <div class="container-fluid">
        <!-- Detalles del Proyecto -->
        <div class="row justify-content-center">
            <div class="col-12 col-lg-10 col-xl-12">
                <div class="card shadow">
                    <div class="card-body p-5">
                        <div class="row d-flex justify-content-center text-center mb-4">
                            <div class="col-md-2">
                                <p class="small text-muted text-uppercase">Cliente</p>
                                <p class="mb-4">{{ client }}</p>
                            </div>
                            <div class="col-md-2">
                                <p class="small text-muted text-uppercase">Propietario del Proyecto</p>
                                <p class="mb-4">{{ employee }}</p>
                            </div>
                            <div class="col-md-2">
                                <p class="small text-muted text-uppercase">Descripción</p>
                                <p class="mb-4">{{ description }}</p>
                            </div>
                            <div class="col-md-2">
                                <p class="small text-muted text-uppercase">Estado</p>
                                <p class="mb-4">{{ status }}</p>
                            </div>
                            <div class="col-md-2">
                                <p class="small text-muted text-uppercase">Vehiculo</p>
                                <p class="mb-4">{{ car }}</p>
                            </div>
                        </div>

                        <div class="row d-flex justify-content-center text-center">
                            <div class="col-md-2">
                                <p class="small text-muted text-uppercase">Fecha de Inicio</p>
                                <p class="mb-4">{{ start_date }}</p>
                            </div>
                            <div class="col-md-2">
                                <p class="small text-muted text-uppercase">Fecha Finalización</p>
                                <p class="mb-4">{{ end_date }}</p>
                            </div>
                            <div class="col-md-2">
                                <p class="small text-muted text-uppercase">Fecha de Creación</p>
                                <p class="mb-4">{{ created_at }}</p>
                            </div>
                            <div class="col-md-2">
                                <p class="small text-muted text-uppercase">Fecha de Actualización</p>
                                <p class="mb-4">{{ updated_at }}</p>
                            </div>
                            <div class="col-md-2">
                                <p class="small text-muted text-uppercase">Actualizado por</p>
                                <p class="mb-4">{{ updated_by }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <br><br>

    <!-- Sección de Tareas -->
    <div class="container-fluid">
        <div class="col-12">
            <h2 class="h3 mb-3 page-title text-center">Tareas</h2>
            <div class="row mb-3 mx-3">
                <div class="col-md-12 d-flex justify-content-between align-items-center">
                    <!-- Formulario de búsqueda alineado a la izquierda -->
                    <form method="GET" action="{% url 'projects:tasks' %}" class="form-inline d-flex">
                        <input name="search" class="form-control mr-2" type="search" placeholder="Buscar">
                        <button type="submit" class="btn btn-outline-success mx-2">Buscar</button>
                    </form>
            
                    <!-- Botón "Agregar Cliente" alineado a la derecha -->
                    <button type="button" class="btn btn-primary button-41" style="min-width: 150px;" 
                        data-bs-toggle="modal" data-bs-target="#addTaskModal">
                        Agregar Tarea
                    </button>
                </div>
            </div>
            <table class="table border table-hover bg-white text-center">
                <thead>
                    <tr>
                        <th>Titulo</th>
                        <th>Descripcion</th>
                        <th>Empleado</th>
                        <th>Estado</th>
                        <th>Fecha Inicio</th>
                        <th>Fecha Fin</th>
                        <th>Ultima Actualizacion</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in tasks %}
                    <tr>
                        <td>{{ task.title }}</td>
                        <td>{{ task.description }}</td>
                        <td>{{ task.employee }}</td>
                        <td>{{ task.status }}</td>
                        <td>{{ task.start_date }}</td>
                        <td>{{ task.end_date|default:"-" }}</td>
                        <td>{{ task.updated_at|default:"-" }}</td>
                        <td>
                            <a href="{% url 'projects:task_details' task.id %}" class="btn btn-info btn-sm">
                                Ver
                            </a>
                            <!-- Botón para abrir el modal de edición -->
                            <button type="button" class="btn btn-primary btn-sm edit-task-btn" 
                                data-bs-toggle="modal" data-bs-target="#editTask"
                                data-task-id="{{ task.id }}"
                                data-title="{{ task.title }}"
                                data-description="{{ task.description }}"
                                data-employee="{{ task.employee.id }}"
                                data-start-date="{{ task.start_date|date:'Y-m-d' }}"
                                data-end-date="{{ task.end_date|date:'Y-m-d'|default_if_none:'' }}"
                                data-status="{{ task.status }}"
                                data-project-id="{{ task.project.id }}">
                                Editar
                            </button>
                            <!-- Botón para abrir el modal de confirmación de eliminación -->
                            <button type="button" class="btn btn-danger btn-sm delete-task-btn"
                                data-bs-toggle="modal" data-bs-target="#deleteTaskModal"
                                data-task-id="{{ task.id }}">
                                Eliminar
                            </button>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="8" class="text-center">El proyecto no tiene tareas.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="pagination-container">
                <button id="prev-page-btn" class="btn btn-secondary btn-sm">Previous</button>
                <span id="current-page" class="mx-2"></span>
                <button id="next-page-btn" class="btn btn-secondary btn-sm">Next</button>
            </div>
        </div>
    </div>
    {% include 'create_task.html' %}
    {% include 'update_task.html' %}
    {% include 'delete_task.html' %}
    {% include 'update_project.html' %}
    
</main>

{% endblock %}