clientdata/urls.py
from django.urls import path, include
from .views import *
from . import views


urlpatterns = [
    path('client/<int:pk>', views.client_data, name='ClientData'),
    path('clients/', ClientsList.as_view(), name='clients'),
    path('clients/add/', AddClient.as_view(), name='add_client'),
    path('clients/edit/<int:pk>/', UpdateClient.as_view(), name='edit_client'),
    path('clients/delete/<int:pk>/', DeleteClient.as_view(), name='delete_client'),
    path ('cars', CarsView.as_view(), name='cars'),
    path ('cars/add_car/', AddCar.as_view(), name='add_car'),
    path ('cars/edit_car/<int:pk>/', UpdateCar.as_view(), name='edit_car'),
    path ('cars/delete/<int:pk>/', DeleteCar.as_view(), name='delete_car'),
    path ('car/<int:pk>/', views.car_data, name='CarData')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('frontend.urls', 'frontend'), namespace='frontend')),
    path('projects/', include(('projects.urls', 'projects'), namespace='projects')),
    path('management/', include(('management.urls', 'management'), namespace='management')),
    path('clientdata/', include(('clientdata.urls', 'clientdata'), namespace='clientdata')),
    path('employees/', include(('employees.urls', 'employees'), namespace='employees')),
    path('frontend/', include(('frontend.urls', 'frontend'), namespace='frontend')),
]

employees/urls.py
from django.urls import path, include
from .views import *
from . import views


urlpatterns = [
    path('', EmployeesList.as_view(), name='employees'),
    path('add/', AddEmployee.as_view(), name='add_employee'),
    path('edit/<int:pk>/', UpdateEmployee.as_view(), name='edit_employee'),
    path('delete/<int:pk>/', DeleteEmployee.as_view(), name='delete_employee'),
    
]

frontend/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='frontend:login'), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

projects/urls.py
from django.urls import path, include
from .views import *
from . import views


urlpatterns = [
    path('', ProjectsView.as_view(), name='projects'),
    path('add/', AddProject.as_view(), name='add_project'),
    path('edit/<int:pk>/', views.edit_project, name='edit_project'),
    path('delete/<int:pk>/', DeleteProject.as_view(), name='delete_project'),
    path('project_details/<int:pk>/', ProjectDetails.as_view(), name='project_details'),
    path('tasks/', Tasks.as_view(), name='tasks'),
    path('task/add_task/', Createtask.as_view(), name='add_task'),
    path('task/edit_task/<int:task_id>/', views.edit_task, name='edit_task'),
    path('task/delete/<int:pk>/', Deletetask.as_view(), name='delete_task'),
    path('task/task_details/<int:pk>/', ViewTask.as_view(), name='task_details'),
    path('task/task_details/add_comment/', CreateComment.as_view(), name='add_comment'),
    path('task/task_details/edit_comment/<int:pk>/', UpdateComment.as_view(), name='edit_comment'),
    path('task/task_details/delete_comment/<int:pk>/', DeleteComment.as_view(), name='delete_comment'),
    path('email/', email_report, name='email_report'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Top Cauchos</title>
    <link href="https://cdn.lineicons.com/4.0/lineicons.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/charts.css' %}">
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}">
    <link rel="stylesheet" href="{% static 'css/popup.css' %}">
</head>

<body>
    <div class="wrapper">
        <aside id="sidebar" class="expand">
            <div class="d-flex">
                <button class="toggle-btn" type="button">
                    <i class="lni lni-grid-alt"></i>
                </button>
                <div class="sidebar-logo">
                    <a href="#">Menu</a>
                </div>
            </div>
            <ul class="sidebar-nav">
                <li class="sidebar-item">
                    <a href="{% url 'frontend:index' %}" class="sidebar-link">
                        <i class="lni lni-layout"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="{% url 'clientdata:clients' %}" class="sidebar-link">
                        <i class="bi bi-people"></i>
                        <span>Clientes</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="{% url 'clientdata:cars' %}" class="sidebar-link">
                        <i class="bi bi-car-front"></i>
                        <span>Vehiculos</span>
                    </a>
                </li>
                <!-- Menú desplegable de Trabajos -->
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link" data-bs-toggle="collapse" data-bs-target="#trabajosSubmenu" aria-expanded="false" aria-controls="trabajosSubmenu">
                        <i class="bi bi-list-ul"></i>
                        <span>Trabajos</span>
                    </a>
                    <!-- Submenú con opciones -->
                    <ul id="trabajosSubmenu" class="collapse">
                        <li>
                            <a href="{% url 'projects:projects' %}" class="sidebar-link">
                                <i class="bi bi-dot"></i>
                                <span>Proyectos</span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'projects:tasks' %}" class="sidebar-link">
                                <i class="bi bi-dot"></i>
                                <span>Tareas</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="sidebar-item">
                    <a href="{% url 'employees:employees' %}" class="sidebar-link">
                        <i class="bi bi-person"></i>
                        <span>Empleados</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="{% url 'management:notifications' %}" class="sidebar-link">
                        <i class="bi bi-chat-dots"></i>
                        <span>Notificaciones</span>
                    </a>
                </li>
                {% if request.user.is_superuser or request.user.is_staff %}
                    <li class="sidebar-item">
                        <a href="{% url 'admin:index' %}" class="sidebar-link">
                            <i class="bi bi-cpu"></i>
                            <span>Admin Panel</span>
                        </a>
                    </li>
                {% endif %}
                <form method="POST">
                    {% csrf_token %}
                    <li class="sidebar-item">
                        <a href="#" id="logout-btn" class="sidebar-link">
                            <i class="bi bi-box-arrow-left"></i>
                            <span>Salir</span>
                        </a>
                    </li>
                </form>
            </ul>
        </aside>
        <div class="body-content">
            <div class="container-fluid text" style="text-align: right;">
                <a style="text-align: right; text-decoration:solid;">
                    <span>Usuario Conectado: {{ user.username }}</span>
                </a>
            </div>
            <div class="container-fluid text-center">
                <img src="{% static 'img/LOGO_TOPCAUCHOS.png' %}" alt="Logo" class="logo" width="150px" height="100px">
            </div>
            <div class="container-fluid text-center titlepage">
                <h1>Top Cauchos Management</h1>
            </div>
            <div class="container-fluid text-center titlecontainer">
                <h1>{%block title %}{%endblock%}</h1>
            </div>
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-info" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
            {%block content %}
                <div id="modal-container"></div>
            {%endblock %}
            
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/charts.js' %}"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/5.6.0/echarts.min.js"></script>
    <script src="https://unpkg.com/htmx.org@1.9.10" integrity="sha384-D1QkvX9nZnlBWr8LUsgZ3j5XGgVHRXWnNRG/yJxYemUADx5vE7zl9RrEgE9I1z9f" crossorigin="anonymous"></script>
    <script>
        document.getElementById('logout-btn').addEventListener('click', function(event) {
            event.preventDefault();  // Evita que el enlace navegue
    
            // Crear un formulario dinámicamente
            var form = document.createElement('form');
            form.method = 'POST';
            form.action = '{% url "frontend:logout" %}';  // La URL de cierre de sesión
    
            // Agregar el token CSRF
            var csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
            var csrfInput = document.createElement('input');
            csrfInput.type = 'hidden';
            csrfInput.name = 'csrfmiddlewaretoken';
            csrfInput.value = csrfToken;
            form.appendChild(csrfInput);
    
            // Enviar el formulario
            document.body.appendChild(form);
            form.submit();
        });
    </script>
</body>

</html>